# Generated by Django 5.2.17 on 2026-09-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trough',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['loading', 'ready', 'withering'])), name='trough_status_valid'),
        ),
    ]
